### PR TITLE
send interval

### PR DESCRIPTION
**Pull request by yasushisakai**
Please take this PR as a grain of salt.

Note this is not a ```sleep``` discarding later data within time frame, it holds and sends data that ends up within ```SEND_INTERVAL```.

Scanner still needs to do hard work inside each while loop.

### CODE REVIEW

**Comment by RELNO** [comment]
When running it breaks here:

```  
File "/CityScope_Scanner_Python/scanner/modules.py", line 58, in send_over_UDP
    last_sent = time.now()
AttributeError: module 'time' has no attribute 'now'
```

**Comment by RELNO** [comment]
`from datetime import datetime` fixes that, but then:

```
  File "/CityScope_Scanner_Python/scanner/modules.py", line 73, in send_over_UDP
    if (grid != old_grid or slider != old_slider) and datetime.now() - last_sent > SEND_INTERVAL:
TypeError: '>' not supported between instances of 'datetime.timedelta' and 'int'

```

**Comment by yasushisakai** [comment]
Fixed it, now we have .pycache ....

**Comment by RELNO** [comment]
It works, however I'm not sure how it would affect the slider responsiveness. What I suspect is that this forces a 30ms delay to both scanner and slider interaction. While it's acceptable for scanner, slider should not be delayed.

**Comment by RELNO** [comment]
merged, will test on machine for slider responsiveness.

**Pull request merged**
